services:
  max-bot:
    build: .
    container_name: max-bot
    volumes:
      - ./logs:/var/www/html/logs
      - ./chats.csv:/var/www/html/chats.csv
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
      - vi-common_vi
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vi-common_vi"
      - "traefik.http.routers.max-bot.rule=Host(`sender-bot.vi.gov45.ru`)"
      - "traefik.http.routers.max-bot.entrypoints=web"
      - "traefik.http.routers.max-bot-secure.rule=Host(`sender-bot.vi.gov45.ru`)"
      - "traefik.http.routers.max-bot-secure.entrypoints=websecure"
      - "traefik.http.routers.max-bot-secure.tls=true"
      - "traefik.http.services.max-bot.loadbalancer.server.port=80"

  db:
    image: mariadb:10.11
    container_name: max-bot-db
    environment:
      MARIADB_DATABASE: max_bot
      MARIADB_USER: maxbot
      MARIADB_PASSWORD: maxbot_password
      MARIADB_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  vi-common_vi:
    external: true